# deault
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
AUDIO_ENABLE = no

# added setteing
VIA_ENABLE = yes
EXTRAKEY_ENABLE = yes
MOUSEKEY_ENABLE = yes
COMBO_ENABLE = yes

CONSOLE_ENABLE = NO

DYNAMIC_MACRO_ENABLE = no
LEADER_ENABLE = no
TAP_DANCE_ENABLE = no
